# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_career', '0008_auto_20160418_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_year',
            field=models.BooleanField(default=False, help_text='Displays how long the current position was held.', verbose_name='Show Year'),
        ),
    ]
